[profile.default]
solc-version = "0.8.24"
evm_version = "cancun"
libs = ['lib']
optimizer = true
optimizer_runs = 420_000
fuzz_max_global_rejects = 420_000

gas_reports = [
    "Contract"
]

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts",
    "@lido/=lib/lido-l2-with-steth/contracts/"
]